### PR TITLE
 Fix parsing of unknown types and types with multiple identifiers 

### LINKED ISSUE #33: Number of columns counted is wrong
CREATE TABLE t (c1 CHARACTER VARYING, c2 UUID, c3 TIMESTAMP)

https://go.dev/play/p/4341fFWS8ly

### PR DESCRIPTION
**Pull request by Elara6331**
SQLite allows the use of any string as a type. It also allows having multiple identifiers in types, as can be seen in this test I ran:

```
sqlite> .headers on
sqlite> CREATE TABLE tbl2 (field X Y Z NOT NULL);
sqlite> PRAGMA table_info(tbl2);
cid|name|type|notnull|dflt_value|pk
0|field|X Y Z|1||0
```

Currently, the parser can handle unknown types in `CAST` expressions, but not `CREATE TABLE` statements, because of the `isTypeName` condition here:

https://github.com/rqlite/sql/blob/c33fce571d190277ddf2aa763240a3462699a588/parser.go#L381

This PR removes that condition, and modifies the parser so that it can parse types with multiple identifiers. It also adds tests to make sure that these changes work properly.

Fixes #33

### CODE REVIEW

File: parser.go [hunk 1]
```diff
@@ -378,7 +378,7 @@ func (p *Parser) parseColumnDefinition() (_ *ColumnDefinition, err error) {
 		return &col, err
 	}
 
-	if _, tok, lit := p.peekScan(); tok == IDENT && isTypeName(lit) {
+	if tok := p.peek(); tok == IDENT {
```
Comment (otoolep) [inline parser.go:381]: Do you think the logic was too strict previously?

**Comment by otoolep** [comment]
https://www.sqlite.org/syntax/type-name.html

Seems like the railroad diagram above concurs with your statement. Interesting, I wonder why SQLite supports this.

File: parser.go (hunk 1 above)
Comment (Elara6331) [reply parser.go:381]: It was. That's what was causing types like `UUID` to be detected as new columns.

File: parser.go [hunk 2]
```diff
@@ -1225,8 +1225,20 @@ func (p *Parser) parseIdent(desc string) (*Ident, error) {
...
+			return &typ, err
+		}
+		if typ.Name == nil {
+			typ.Name = typeName
+		} else {
+			typ.Name.Name += " " + typeName.Name
+		}
+	}
+
+	if typ.Name == nil {
```
Comment (otoolep) [inline parser.go:1240]: The only way this will not be nil is if `p.peek() != IDENT`, right? If so should you just roll this into the if block above?

Comment (Elara6331) [reply parser.go:1240]: The block above is a for loop, not an if statement

Comment (otoolep) [reply parser.go:1240]: D'oh! You're right, how did I miss that.

File: parser.go [hunk 3]
```diff
@@ -1225,8 +1225,20 @@ func (p *Parser) parseIdent(desc string) (*Ident, error) {
 
 func (p *Parser) parseType() (_ *Type, err error) {
 	var typ Type
-	if typ.Name, err = p.parseIdent("type name"); err != nil {
-		return &typ, err
+	for p.peek() == IDENT {
```
Comment (otoolep) [inline parser.go:1228]: What is the idea behind the for loop? Only return the last type?

Comment (Elara6331) [reply parser.go:1228]: The for loop appends each identifier to the type name string. You can see the effect of that in the tests here:

https://github.com/rqlite/sql/blob/306085970cf55ee6b718b2ff7bb77a2bf4463b9a/parser_test.go#L459

I thought about using a slice of `*sql.Ident` instead, but that would break a lot of the code in this library, which means this would be a much bigger and more complicated PR, and it would be a breaking change for anyone who imports this library. If you'd like me to do that instead though, I can.

**Comment by otoolep** [comment]
This works for me -- thanks.
